<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <title>Chat Sections</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <script src="https://js.pusher.com/8.2.0/pusher.min.js"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" rel="stylesheet">
</head>
<style>
  body,
  html {
    margin: 0;
    padding: 0;
    height: 100%;
    background: #ece5dd;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
  }
  
  /* Dropdown menu for ellipsis */
  .menu-dropdown {
    display: none;
    position: absolute;
    background: white;
    border-radius: 4px;
    box-shadow: 0 2px 5px rgba(0,0,0,0.2);
    min-width: 200px;
    z-index: 1000;
    right: 16px;
    top: 60px;
  }
  .menu-dropdown.show { display: block; }
  .menu-dropdown div { 
    padding: 14px 20px; 
    cursor: pointer; 
    font-size: 14px;
    color: #303030;
    display: flex;
    align-items: center;
    transition: background 0.2s ease;
  }
  .menu-dropdown div:hover { background: #f5f5f5; }
  .menu-dropdown div i { color: #666; font-size: 16px; }
  .menu-dropdown div:first-child { border-radius: 4px 4px 0 0; }
  .menu-dropdown div:last-child { border-radius: 0 0 4px 4px; }
</style>

<body class="font-sans">
  <div class="relative w-full h-screen overflow-hidden bg-white md:flex">
    <!-- LEFT: Chat list -->
    <section class="relative w-full h-screen flex flex-col overflow-hidden bg-white md:w-[380px] md:border-r md:border-gray-100">
      <!-- Header -->
      <header class="flex items-center p-4 bg-white border-b border-gray-100">
        <h1 class="text-grey-600 font-bold text-xl">Chatting</h1>
        <button aria-label="Camera" class="ml-auto mr-4 text-gray-600 hover:text-gray-800">
        <!-- Icons
         <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" >
          <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
          <circle cx="12" cy="13" r="4"></circle>
        </svg> -->
        </button>
        <button aria-label="More options" class="text-gray-600 hover:text-gray-800" id="ellipsisBtn">
          <i class="fa-solid fa-ellipsis-vertical text-xl"></i>
        </button>
      </header>

    <!-- Dropdown menu -->
    <div id="menuDropdown" class="menu-dropdown">
      <div id="logoutBtn">
        <i class="fa-solid fa-right-from-bracket" style="margin-right: 12px; width: 16px;"></i>
        <span>Logout</span>
      </div>
    </div>

      <!-- Chat List -->
      <main class="flex-1 overflow-auto bg-white">
        <ul id="chatList" class="">
          <!-- Chat items (will be generated by JS or static) -->
        </ul>
      </main>

    </section>

    <!-- RIGHT: Chat panel (desktop only) -->
    <section class="hidden md:flex flex-1 h-screen bg-[#ece5dd]">
      <!-- Empty state (shown when no contact clicked) -->
      <div id="chatEmptyState" class="flex-1 flex items-center justify-center">
        <div class="text-center text-gray-600">
          <div class="mb-6 flex justify-center">
            <img src="https://img.icons8.com/?size=100&id=54385&format=png&color=000000" alt="Chat Icon" class="w-32 h-32 opacity-70">
          </div>
          <div class="text-4xl font-semibold text-gray-700">BK - SMKN 1 CIAMIS CHAT</div>
          <!-- <div class="mt-3 text-sm text-gray-500">Pilih kontak untuk mulai chat.</div> -->
          <div class="mt-6 text-xs text-gray-400">Your personal messages are end-to-end encrypted</div>
        </div>
      </div>

      <!-- Embedded chatroom (shown after clicking a contact) -->
      <iframe
        id="chatIframe"
        title="Chat Room"
        class="hidden w-full h-full border-0"
        src="about:blank"
      ></iframe>
    </section>

    <!-- Context menu (desktop) -->
    <div id="chatItemMenu" class="hidden fixed bg-white rounded-md shadow-lg z-[2000] min-w-[220px] overflow-hidden">
      <!-- <button id="selectMessagesOption" class="w-full text-left px-5 py-3 hover:bg-gray-100 text-gray-800 flex items-center gap-3">
        <i class="fa-regular fa-square-check text-gray-500"></i>
        <span>Select messages</span>
      </button> -->
      <button id="closeChatOption" class="w-full text-left px-5 py-3 hover:bg-gray-100 text-gray-800 flex items-center gap-3">
        <i class="fa-regular fa-circle-xmark text-gray-500"></i>
        <span>Close chat</span>
      </button>
    </div>

    <!-- Bottom Nav
    <nav class="flex justify-around border-t border-gray-200 p-3 text-gray-600">
      <button class="flex flex-col items-center text-green-600">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mb-1" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"></path>
        </svg>
        Chats
      </button>
      <button class="flex flex-col items-center hover:text-green-600">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mb-1" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <path d="M12 20h9"></path>
          <path d="M12 4h9"></path>
          <path d="M4 9h16"></path>
          <path d="M4 15h16"></path>
        </svg>
        Updates
      </button>
      <button class="flex flex-col items-center hover:text-green-600">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mb-1" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <circle cx="12" cy="12" r="10"></circle>
          <path d="M14.31 8l5.74 9.94"></path>
          <path d="M9.69 8h11.48"></path>
          <path d="M7.38 12l5.74-9.94"></path>
          <path d="M9.69 16L3.95 6.06"></path>
          <path d="M14.31 16H2.83"></path>
          <path d="M16.62 12l-5.74 9.94"></path>
        </svg>
        Communities
      </button>
      <button class="flex flex-col items-center hover:text-green-600 relative">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mb-1" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <path d="M15 10l4.553-2.276a1 1 0 0 1 1.447.894v4.764a1 1 0 0 1-1.447.894L15 14M9 21V3a2 2 0 0 1 4 0v18"></path>
        </svg>
        Settings
        <div class="absolute bottom-6 right-4 bg-green-600 rounded-full h-4 w-4 border-2 border-white"></div>
      </button>
    </nav> -->
  </div>

  <script>
    // Data from database - Load via API
    let chats = [];

    const currentViewerRole = @json(auth()->user()->role ?? 'guru');
    const roomBasePath = @json($roomBasePath ?? '/room');

    const chatSessionsRoute = '{{ route("chat.sessions") }}';
    
    // Load sessions from API on page load
    async function loadSessions() {
      try {
        const response = await fetch(chatSessionsRoute);
        const result = await response.json();
        
        if (result.success && result.data) {
          chats = result.data.map((session) => ({
            id: session.id || session.phone_number,
            name: session.contact_name || session.room_name || session.phone_number || 'General',
            message: session.last_message || '',
            time: '',
            last_activity: session.last_activity || new Date().toISOString(),
            avatar: session.avatar || 'https://img.icons8.com/?size=96&id=Z1n6MSkfdSgd&format=png&color=9E9E9E',
            unread: session.unread_count || 0,
            status: session.status || 'active',
            last_message_status: session.last_message_status || (session.direction === 'out' ? 'sent' : 'delivered'),
            last_message_direction: session.direction || 'in',
            phone_number: session.phone_number
          }));
          
          renderChats();
        }
      } catch (error) {
        console.error('Failed to load sessions:', error);
      }
    }
    
    // Call on page load
    loadSessions();


    const chatListEl = document.getElementById('chatList');
    const chatEmptyStateEl = document.getElementById('chatEmptyState');
    const chatIframeEl = document.getElementById('chatIframe');

    let currentOpenSessionId = null;
    let refreshTimer = null;

    // Realtime (Soketi / Pusher protocol)
    const broadcastConnection = @json(config('broadcasting.default'));
    const pusherKey = @json(config('broadcasting.connections.pusher.key'));
    const pusherHost = @json(config('broadcasting.connections.pusher.options.host'));
    const pusherPort = Number(@json(config('broadcasting.connections.pusher.options.port')) || 6001);
    const pusherScheme = @json(config('broadcasting.connections.pusher.options.scheme'));
    const pusherCluster = @json(config('broadcasting.connections.pusher.options.cluster'));
    const realtimeEnabled = broadcastConnection === 'pusher' && !!pusherKey && typeof window.Pusher !== 'undefined';
    let sessionsChannel = null;

    const chatItemMenuEl = document.getElementById('chatItemMenu');
    const selectMessagesOptionEl = document.getElementById('selectMessagesOption');
    const closeChatOptionEl = document.getElementById('closeChatOption');
    const fullModalOverlayEl = document.getElementById('fullModalOverlay');
    let menuTargetSessionId = null;

    function formatChatListTime(isoString) {
      if (!isoString) return '';
      const d = new Date(isoString);
      if (Number.isNaN(d.getTime())) return '';

      const now = new Date();

      // Use local dates for day comparisons
      const startOfToday = new Date(now.getFullYear(), now.getMonth(), now.getDate());
      const startOfThatDay = new Date(d.getFullYear(), d.getMonth(), d.getDate());
      const diffMs = startOfToday.getTime() - startOfThatDay.getTime();
      const diffDays = Math.floor(diffMs / (24 * 60 * 60 * 1000));

      // Today -> hh:mm am/pm
      if (diffDays === 0) {
        const timeStr = new Intl.DateTimeFormat('en-US', {
          hour: '2-digit',
          minute: '2-digit',
          hour12: true,
        }).format(d);

        // Normalize to `06:20 am` (lowercase)
        return String(timeStr).replace(/\s+/g, ' ').trim().toLowerCase();
      }

      // Less than a week -> weekday in English
      if (diffDays > 0 && diffDays < 7) {
        return new Intl.DateTimeFormat('en-US', { weekday: 'long' }).format(d);
      }

      // 7+ days (or future/unknown) -> dd/mm/yyyy
      const dd = String(d.getDate()).padStart(2, '0');
      const mm = String(d.getMonth() + 1).padStart(2, '0');
      const yyyy = String(d.getFullYear());
      return `${dd}/${mm}/${yyyy}`;
    }

    function hideChatItemMenu() {
      if (!chatItemMenuEl) return;
      chatItemMenuEl.classList.add('hidden');
      menuTargetSessionId = null;
    }

    function showChatItemMenu(x, y, sessionId) {
      if (!isDesktopMode() || !chatItemMenuEl) return;
      menuTargetSessionId = String(sessionId);
      // Clamp menu to viewport
      const menuW = chatItemMenuEl.offsetWidth || 180;
      const menuH = chatItemMenuEl.offsetHeight || 52;
      const vw = window.innerWidth;
      const vh = window.innerHeight;
      const left = Math.max(8, Math.min(x, vw - menuW - 8));
      const top = Math.max(8, Math.min(y, vh - menuH - 8));
      chatItemMenuEl.style.left = `${left}px`;
      chatItemMenuEl.style.top = `${top}px`;
      chatItemMenuEl.classList.remove('hidden');
    }

    function showFullOverlay() {
      if (!fullModalOverlayEl) return;
      fullModalOverlayEl.classList.remove('hidden');
    }

    function hideFullOverlay() {
      if (!fullModalOverlayEl) return;
      fullModalOverlayEl.classList.add('hidden');
    }

    function isDesktopMode() {
      return window.matchMedia && window.matchMedia('(min-width: 768px)').matches;
    }

    function openChatInPanel(sessionId) {
      currentOpenSessionId = String(sessionId);
      
      // Find chat data
      const chat = chats.find(c => String(c.id) === String(sessionId));
      // Use sessionId (room_name) as the canonical room identifier
      const roomId = String(sessionId);
      const name = chat ? chat.name : '';
      const encodedRoomId = encodeURIComponent(roomId);
      const encodedName = encodeURIComponent(String(name || ''));
      
      if (!isDesktopMode()) {
        window.location.href = `${roomBasePath}/${encodedRoomId}?contact_name=${encodedName}&viewer_role=${encodeURIComponent(currentViewerRole)}`;
        return;
      }

      if (chatEmptyStateEl) chatEmptyStateEl.classList.add('hidden');
      if (chatIframeEl) {
        chatIframeEl.classList.remove('hidden');
        chatIframeEl.src = `${roomBasePath}/${encodedRoomId}?contact_name=${encodedName}&embed=1&viewer_role=${encodeURIComponent(currentViewerRole)}`;
      }

      // Keep URL shareable without leaving page
      try {
        const url = new URL(window.location.href);
        url.searchParams.set('sesi_id', String(sessionId));
        url.searchParams.set('phone', roomId);
        if (chat && chat.name) {
          url.searchParams.set('contact_name', encodeURIComponent(chat.name));
        }
        window.history.replaceState(null, '', url.toString());
      } catch (_) {
        // ignore
      }
    }

    function closeChatPanel() {
      currentOpenSessionId = null;

      if (chatIframeEl) {
        chatIframeEl.src = 'about:blank';
        chatIframeEl.classList.add('hidden');
      }
      if (chatEmptyStateEl) chatEmptyStateEl.classList.remove('hidden');

      try {
        const url = new URL(window.location.href);
        url.searchParams.delete('sesi_id');
        url.searchParams.delete('phone');
        url.searchParams.delete('contact_name');
        window.history.replaceState(null, '', url.toString());
      } catch (_) {
        // ignore
      }
    }

    async function refreshSessions() {
      try {
        const res = await fetch(chatSessionsRoute, { headers: { 'Accept': 'application/json' } });
        const data = await res.json().catch(() => ({}));
        if (!res.ok || data.success !== true || !Array.isArray(data.data)) return;

        // Replace contents of chats array in-place (keeps references stable)
        chats.length = 0;
        data.data.forEach((session) => {
          chats.push({
            id: session.id || session.phone_number,
            name: session.contact_name || session.room_name || session.phone_number || 'General',
            message: session.last_message || '',
            time: '',
            last_activity: session.last_activity || new Date().toISOString(),
            avatar: session.avatar || 'https://img.icons8.com/?size=96&id=Z1n6MSkfdSgd&format=png&color=9E9E9E',
            unread: session.unread_count || 0,
            status: session.status || 'active',
            last_message_status: session.last_message_status || (session.direction === 'out' ? 'sent' : 'delivered'),
            last_message_direction: session.direction || 'in',
            phone_number: session.phone_number
          });
        });

        renderChats();
      } catch (_) {
        // ignore
      }
    }

    function startAutoRefresh() {
      // Polling disabled (use realtime via Soketi/Pusher instead)
    }

    function initRealtime() {
      if (!realtimeEnabled) return;
      if (sessionsChannel) return;

      const forceTLS = pusherScheme === 'https';

      const pusher = new Pusher(pusherKey, {
        cluster: pusherCluster || undefined,
        wsHost: pusherHost || window.location.hostname,
        wsPort: pusherPort,
        wssPort: pusherPort,
        forceTLS,
        disableStats: true,
        enabledTransports: ['ws', 'wss'],
      });

      sessionsChannel = pusher.subscribe('chat-sessions');
      sessionsChannel.bind('chat.message.created', () => {
        refreshSessions();
      });

      sessionsChannel.bind('chat.messages.read', () => {
        refreshSessions();
      });
    }

    function renderChats(filter = '') {
      chatListEl.innerHTML = '';
      const filteredChats = chats.filter(chat =>
        String(chat.name || '').toLowerCase().includes(filter.toLowerCase()) ||
        String(chat.message || '').toLowerCase().includes(filter.toLowerCase())
      );

      filteredChats.forEach(chat => {
        const li = document.createElement('li');
        li.className = 'flex items-center px-4 py-3 hover:bg-gray-50 cursor-pointer border-b border-gray-100';
        let clickTimer = null;
        li.addEventListener('click', (e) => {
          // On desktop, delay single-click so dblclick can open menu without opening chat
          if (!isDesktopMode()) {
            openChatInPanel(chat.id);
            return;
          }
          if (clickTimer) clearTimeout(clickTimer);
          clickTimer = setTimeout(() => openChatInPanel(chat.id), 220);
        });

        li.addEventListener('dblclick', (e) => {
          if (!isDesktopMode()) return;
          e.preventDefault();
          e.stopPropagation();
          if (clickTimer) clearTimeout(clickTimer);
          showChatItemMenu(e.clientX, e.clientY, chat.id);
        });

        li.addEventListener('contextmenu', (e) => {
          if (!isDesktopMode()) return;
          e.preventDefault();
          e.stopPropagation();
          if (clickTimer) clearTimeout(clickTimer);
          // Intentionally do nothing: no Edge menu, and no custom menu.
        });

        const direction = String(chat.last_message_direction || 'in');
        const isSelfLastMessage = (String(currentViewerRole) === 'guru')
          ? (direction === 'out')
          : (direction === 'in');

        const checkColor = (String(chat.last_message_status || 'sent') === 'read') ? '#4fc3f7' : '#999';
        const checkIcon = isSelfLastMessage
          ? `<i class="fa-solid fa-check-double" style="font-size:12px;color:${checkColor};margin-right:6px;"></i>`
          : '';

        const formattedTime = chat.last_activity ? formatChatListTime(chat.last_activity) : (chat.time || '');
        
        // Tentukan badge berdasarkan status
        let statusBadge = '';
        let statusColor = '';
        if (chat.status === 'open') {
          statusBadge = 'Open';
          statusColor = 'bg-yellow-500';
        } else if (chat.status === 'pending') {
          statusBadge = 'Pending';
          statusColor = 'bg-blue-500';
        } else if (chat.status === 'closed') {
          statusBadge = 'Closed';
          statusColor = 'bg-green-600';
        }

        li.innerHTML = `
  <div class="flex-shrink-0 mr-3">
    <div class="w-11 h-11 rounded-full overflow-hidden ring-2 ring-gray-300 shadow-sm bg-white relative flex items-center justify-center">
      <img
        src="${chat.avatar}"
        alt="${chat.name}"
        class="w-7 h-7 object-contain"
      />
    </div>
  </div>

  <div class="flex-1 min-w-0">
    <div class="flex justify-between items-start mb-1">
      <p class="font-bold text-gray-900 text-base truncate">
        ${chat.name}
      </p>

      ${formattedTime ? `<p class="text-xs ${chat.unread ? 'text-green-600 font-bold' : 'text-gray-500'} whitespace-nowrap flex-shrink-0">
        ${formattedTime}
      </p>` : ''}
    </div>

    ${chat.message ? `<div class="flex items-center justify-between gap-2">
      <p class="flex-1 min-w-0 truncate ${chat.unread ? 'font-bold text-gray-800' : 'text-gray-500'} text-sm leading-tight flex items-center">
        ${checkIcon}<span class="truncate">${chat.message}</span>
      </p>

      ${chat.unread
          ? `<span class="-mt-0.5 bg-green-600 text-white text-xs rounded-full min-w-[20px] h-[20px] flex items-center justify-center px-1.5 font-medium flex-shrink-0">
              ${chat.unread}
            </span>`
          : ''
        }
    </div>` : ''}
  </div>
`;

        chatListEl.appendChild(li);
      });

      if (filteredChats.length === 0) {
        chatListEl.innerHTML = '<li class="p-4 text-center text-gray-400">No chats found</li>';
      }
    }

    function filterChats() {
      const searchValue = document.getElementById('searchInput').value;
      renderChats(searchValue);
    }

    renderChats();
    startAutoRefresh();
    refreshSessions();
    initRealtime();

    // If URL already has params, open it in desktop panel
    try {
      const url = new URL(window.location.href);
      const sesiId = url.searchParams.get('sesi_id');
      const phone = url.searchParams.get('phone');
      const contactName = url.searchParams.get('contact_name');
      
      if (sesiId || phone) {
        // Wait for sessions to load first
        setTimeout(() => {
          if (sesiId) {
            openChatInPanel(sesiId);
          } else if (isDesktopMode() && phone) {
            // Directly open iframe if we have phone
            if (chatEmptyStateEl) chatEmptyStateEl.classList.add('hidden');
            if (chatIframeEl) {
              chatIframeEl.classList.remove('hidden');
              const qs = new URLSearchParams();
              if (contactName) qs.set('contact_name', contactName);
              qs.set('embed', '1');
              qs.set('viewer_role', String(currentViewerRole || ''));
              chatIframeEl.src = `${roomBasePath}/${encodeURIComponent(phone)}?${qs.toString()}`;
            }
          }
        }, 500);
      }
    } catch (_) {
      // ignore
    }

    // Realtime updates from embedded chatroom
    window.addEventListener('message', (event) => {
      if (event.origin !== window.location.origin) return;
      const data = event.data || {};
      if (data.type === 'chat:refreshSessions') {
        refreshSessions();
      }
      if (data.type === 'chat:closePanel') {
        closeChatPanel();
      }

      // Request from embedded iframe: show close-chat menu at cursor
      if (data.type === 'chat:showCloseMenuFromIframe') {
        if (!isDesktopMode()) return;
        if (!chatIframeEl) return;
        const rect = chatIframeEl.getBoundingClientRect();
        const x = rect.left + Number(data.x || 0);
        const y = rect.top + Number(data.y || 0);
        // Use the same menu; session id not needed for close
        showChatItemMenu(x, y, currentOpenSessionId || '');
      }

      if (data.type === 'chat:hideMenuFromIframe') {
        hideChatItemMenu();
      }

      // Show modal overlay from iframe (for desktop split view)
      if (data.type === 'chat:showModalOverlay') {
        showFullOverlay();
      }

      // Hide modal overlay from iframe
      if (data.type === 'chat:hideModalOverlay') {
        hideFullOverlay();
      }

      // Show end session confirmation modal from iframe
      if (data.type === 'chat:showEndSessionModal') {
        if (typeof window.showEndSessionConfirmModal === 'function') {
          window.showEndSessionConfirmModal();
        }
      }

      // Hide end session modal from iframe
      if (data.type === 'chat:hideEndSessionModal') {
        if (typeof window.hideEndSessionConfirmModal === 'function') {
          window.hideEndSessionConfirmModal();
        }
      }
    });

    // Logout
    const logoutBtn = document.getElementById('logoutBtn');
    if (logoutBtn) {
      logoutBtn.addEventListener('click', async () => {
        try {
          const csrf = document.querySelector('meta[name="csrf-token"]')?.content || '';
          await fetch(@json(route('auth.logout')), {
            method: 'POST',
            headers: {
              'X-CSRF-TOKEN': csrf,
              'Accept': 'application/json'
            }
          });
        } catch (_) {
          // ignore
        } finally {
          window.location.href = @json(route('auth.login'));
        }
      });
    }

    // Refresh when window focused (helps if polling paused)
    window.addEventListener('focus', refreshSessions);
    
    // Dropdown menu functionality
    const ellipsisBtn = document.getElementById("ellipsisBtn");
    const menuDropdown = document.getElementById("menuDropdown");
    
    // Toggle dropdown
    ellipsisBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      menuDropdown.classList.toggle("show");
    });
    
    // Close dropdown when clicking outside
    document.addEventListener("click", (e) => {
      if (!menuDropdown.contains(e.target) && e.target !== ellipsisBtn) {
        menuDropdown.classList.remove("show");
      }
    });
    
    // Logout handled by shared modal script (chat-modal.js)

    // Context menu actions
    if (selectMessagesOptionEl) {
      selectMessagesOptionEl.addEventListener('click', () => {
        // UI only for now; just close the menu.
        hideChatItemMenu();
      });
    }
    if (closeChatOptionEl) {
      closeChatOptionEl.addEventListener('click', () => {
        hideChatItemMenu();
        closeChatPanel();
      });
    }

    document.addEventListener('click', (e) => {
      if (!chatItemMenuEl) return;
      if (!chatItemMenuEl.classList.contains('hidden') && !chatItemMenuEl.contains(e.target)) {
        hideChatItemMenu();
      }
    });

    window.addEventListener('resize', hideChatItemMenu);
  </script>

  <script src="{{ asset('js/chat-modal.js') }}"></script>
</body>

</html>