name: Deploy Laravel ke Server (Fresh DB)

on:
  push:
    branches:
      - Zwar  # branch utama

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Setup SSH connection
    - name: Setup SSH connection
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Deploy via SSH
    - name: Deploy to server via SSH
      run: |
        ssh -p 21032 -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
          cd web

          # Sinkron semua file dengan GitHub
          git fetch origin Zwar
          git reset --hard origin/Zwar
          git clean -fd

          # Install dependencies
          composer install --no-interaction --prefer-dist --optimize-autoloader
          npm install
          npm run build

          # Laravel tasks
          php artisan migrate:fresh --seed --force   # Hapus & rebuild semua DB + seed
          php artisan storage:link
          php artisan optimize
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
        "